name: dchat_client
description: A decentralized chat client.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: ^2.8.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^7.0.1
  shared_preferences: ^2.1.1
  basic_utils: ^5.5.4
  http: ^0.13.6
  web_socket_channel: ^2.4.0
  pointycastle: ^3.7.3
  uni_links: ^0.5.1

dev_dependencies:
  drift_dev: ^2.8.2
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
