name: dchat_client
description: A decentralized chat client.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  drift: ^2.8.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  go_router: ^7.0.1
  shared_preferences: ^2.1.1
  basic_utils: ^5.5.4
  http: ^0.13.6
  web_socket_channel: ^2.4.0
  pointycastle: ^3.7.3
  uni_links: ^0.5.1
  otp: ^3.1.4
  sqlite3: ^1.11.1
  drift_dev: ^2.8.2
  qr_flutter: ^4.1.0

flutter_launcher_icons:
  image_path: "assets/images/icon-512.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: true
    image_path: "assets/images/icon-512.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon-512.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon-512.png"

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  # We use this to compile the shared web worker for the web database. This dependency
  # isn't required for most apps. You only need it if you want to target the web, use
  # web workers for drift AND want to compile those web workers through `build_runner`.
  # Either way, using this package with Flutter requires a delicate setup described in
  # `build.yaml`.
  build_web_compilers: ^3.2.2
  build: ^2.2.1

flutter:
  uses-material-design: true
